### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by oddstr13** [oddstr13/jellyfin-plugin-repository-manager#1]
I've pulled some code from [jellyfin/jellyfin-build/build_plugin.py](https://github.com/jellyfin/jellyfin-build/blob/0e9c18994839f317b07735ddac3c99a2c288ca5a/build_plugin.py).

Requesting permission to license under the [Mozilla Public License, version 2.0](http://mozilla.org/MPL/2.0/)

 - [x] @JoshuaBoniface
 - [x] @dkanada

**Comment by dkanada** [comment]
sounds good to me

**Comment by joshuaboniface** [comment]
Permission granted.
