### ISSUE TITLE
Plugins can have invalid version

### ISSUE THREAD

**Issue by crobibero** [oddstr13/jellyfin-plugin-repository-manager#14]
Reported [here](https://github.com/jellyfin/jellyfin/issues/6228)

From Matrix: 
"the version number isn't expanded when provided as a single digit"

**Comment by oddstr13** [comment]
The source of the trouble is me testing this pr (and pushing to my repo); https://github.com/jellyfin/jellyfin-plugin-coverartarchive/pull/8/files
