### ISSUE TITLE
Possible typo in action.yaml script

### ISSUE THREAD

**Issue by neBM** [oddstr13/jellyfin-plugin-repository-manager#181]
Tiny issue here! It appears there may be a typo in your action.yaml:

https://github.com/oddstr13/jellyfin-plugin-repository-manager/blob/a5604d4264a909af827e84026ea8c917f98dc6da/action.yaml#L68

~~DOTNET_FRAMEWORD~~ DOTNET_FRAMEWORK

**Comment by oddstr13** [comment]
Typo, yes, but not an issue, as the undefined variable expands to an empty string regardless.
In the future, please just include the details in the pull-request, instead of creating an issue, and then a pull-request with *an empty description*.
