### ISSUE TITLE
[Discussion] create one or more JPRM GH Actions

### ISSUE THREAD

**Issue by h1dden-da3m0n** [oddstr13/jellyfin-plugin-repository-manager#4]
Hi,

in my experiments with the Plugin CI PRs it crossed my mind that we could create one or two GitHub Actions executing the JPRM:

* one to [build and package the plugin](https://github.com/h1dden-da3m0n/jellyfin-plugin-ldapauth/blob/master/.github/workflows/build-dotnet.yml)
* the other to publish it to a repository?

I took the liberty and played a round a bit and got an initial draft working as a [`composite` action](https://github.com/h1dden-da3m0n/jellyfin-plugin-repository-manager/blob/feat/composite-action/action.yaml) however we could package the JPRM in a container and use it as such in the actions, that would likely end up in separate repos.

Anyway, this issue serves more as a discussion thread if we want to try something in such lines or not.
In case we want to I would be more than happy to provide everything needed, but I wanted to know if you are interested first.

**Comment by h1dden-da3m0n** [comment]
well this has been solved by the move to composite Actions :tada: 
Just need you to crate a tag and I can use it in the update CI PRs for the plugins :wink:

**Comment by ReenigneArcher** [comment]
I didn't want to create an issue for this yet, in case I am doing something stupid... but it appears that the action is failing.

Something changed between last week and now as it was working fine.
![image](https://user-images.githubusercontent.com/42013603/220210981-6f04cc07-f994-4517-a6af-22a5874cfc43.png)

```txt
Building and Packaging
  debug: {'dotnet_config': 'Release', 'dotnet_framework': 'net6.0', 'output': '/tmp/tmpmn14rn8p', 'version': '0.0.0.0'}
  Setting project version to 0.0.0.0
  debug: Old file version: 0.0.0.0
  debug: Old assembly version: 0.0.0.0
  Setting project framework to net6.0
  debug: Old framework: net6.0
  debug: ['run_os_command', ['dotnet', 'clean', '--configuration=Release', '--framework=net6.0'], None, False, '.']
  debug: ['run_os_command', ['dotnet', 'restore', '--no-cache'], None, False, '.']
  debug: ['run_os_command', ['dotnet', 'publish', '--nologo', '--no-restore', '--configuration=Release', '--framework=net6.0', '--output=/tmp/tmpmn14rn8p', '-p:Version=0.0.0.0'], None, False, '.']
  /usr/share/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): error NETSDK1194: The "--output" option isn't supported when building a solution. [/home/runner/work/Themerr-jellyfin/Themerr-jellyfin/Jellyfin.Plugin.Themerr.sln]
```

Any idea?
