### ISSUE TITLE
Plugins grouped by Name instead of ID

### ISSUE THREAD

**Issue by crobibero** [oddstr13/jellyfin-plugin-repository-manager#7]
https://github.com/jellyfin/jellyfin-plugin-tvmaze/issues/8#issuecomment-820571251

tldr: Renamed plugin, now it's listed twice

**Comment by oddstr13** [comment]
Do note that the file path on the repo will change when renaming the plugin, and that this is intentional.
They *should* be grouped by GUID in the manifest however.
