### ISSUE TITLE
Usage documentation?

### ISSUE THREAD

**Issue by hexxone** [oddstr13/jellyfin-plugin-repository-manager#89]
Hi there,

I am trying to automatically Release / Build a Plugin for Jellyfin and the Repository file.
I am using Github Actions and <https://github.com/jellyfin/jellyfin-plugin-template> as a basis.

Unfortunately I could not figure out the proper setup-steps even with this <https://jellyfin.org/posts/plugin-updates/> blog post.

Eventually I figured out I had to do a manual Release for the Action to start running...

But now I run into my current problem: 

on: **call / upload**
`
Error: unexpected status code: 403 {"message":"Resource not accessible by integration","request_id":"5C09:4390:54583:6F39D:64026C75","documentation_url":"https://docs.github.com/rest"}
`

This is the action that failed: <https://github.com/hexxone/TeleJelly/actions/runs/4327567219>

It seems to me that the "GITHUB_TOKEN" is used per default and should be created automatically for every Action Run?

I simply cannot figure out what, if anything, I did wrong and would appreciate if someone had the time to take a glance at it.

Thanks in advance.

**Comment by oddstr13** [comment]
The failing step is the shogo82148/actions-upload-release-asset action https://github.com/hexxone/TeleJelly/actions/runs/4327567219/jobs/7556354811#step:6:1

I'm not sure of why [actions-upload-release-asset](https://github.com/shogo82148/actions-upload-release-asset) failed for you here, but it's quite possibly has to do with repository permissions for uploading release assets?
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

The build step, which uses this repo is completing fine without errors https://github.com/hexxone/TeleJelly/actions/runs/4327567219/jobs/7556347474#step:4:1
Tho, it isn't being feed the correct version number, which will be a problem, you need to update the version number in build.yaml before building the release; https://github.com/hexxone/TeleJelly/blob/main/build.yaml#L4 ,
or supply the version to the action https://github.com/oddstr13/jellyfin-plugin-repository-manager/blob/4a2b165a3dc2cfc392db865a85f23c02e9f78c68/action.yaml#L18

You would probably do best not calling on Jellyfin's actions (which the template does by default), and rather copy the action itself; https://github.com/jellyfin/jellyfin-meta-plugins/blob/master/.github/workflows/publish.yaml
https://github.com/hexxone/TeleJelly/blob/main/.github/workflows/publish.yaml#L11
This way you can modify it to suit your project.

Either way, I consider generic support for GitHub CI (Other than the specific action provided by this repo) to be out of scope here, sorry.
